### ISSUE TITLE
R package

### ISSUE THREAD

**Issue by calderonsamuel** [jincio/decidebien_desarrollo#10]
Hacer un R package para replicar el aplicativo

**Comment by malenamaguina** [comment]
Hola Samuel, qué ayuda necesitas?

**Comment by calderonsamuel** [comment]
@malenamaguina  Hola, aún estoy aprendiendo a usar bien los tags. ¿Te parece bien si asigno esta tarea a tu nombre?

**Comment by jincio** [comment]
Me parece que la organización que hizo malena incluye lo de los tags etc. Voy a cerrar este issue
