### ISSUE TITLE
Error en Log-(Mensaje al final de la página "Filtros")

### ISSUE THREAD

**Issue by jincio** [jincio/decidebien_desarrollo#3]
El Log de shinyapp me dice esto: 

![Screen Shot 2019-12-07 at 12 40 13 PM](https://user-images.githubusercontent.com/11399766/70378488-def36e80-18ee-11ea-88c1-edb4936fd33a.png)

**Comment by calderonsamuel** [comment]
Se debe a que en output$actuali no cierra con "})" hasta después de output$resumen1. Ahora mando un fork para arreglarlo
