### ISSUE TITLE
Actualizar la base de Decidebien.db

### ISSUE THREAD

**Issue by jincio** [jincio/decidebien_desarrollo#9]
En el sript funciones.R el nombre de Lima lo he cortado a Lima+Exterior, pero me parece que no está actualizando la base de datos. Se me ocurre que podemos drop la tabla original y luego crear nuevamente la tabla. ¿Ideas?

**Comment by malenamaguina** [comment]
Hola José, as'i es. Este debería ser un proceso independiente.

**Comment by malenamaguina** [comment]
He abierto un PR para solucionar este issue. Sldos.

**Comment by jincio** [comment]
Gracias Malena,
Ayer traté de actualizar la base con los nuevos nombres de los departamentos pero no lo hizo. No me dió tiempo para ver exactamente cuál es el problema. Corri el nuevo script, no arrojo error, pero tampoco actualizaba la base. Seguiré intentando.
